let express = require("express")
let api = express()
api.use(express.json())
api.use(express.static(__dirname + "/node_modules/axios/dist"))
api.use(express.static(__dirname + "/public"))
let controller = require("./controller")
api.get("/start", controller.start)
api.put("/move", controller.move)
api.listen(3000, controller.listen)