let express = require("express")
let controller = require("./controller")
let api = express()
api.use(express.json())
api.use(express.static(__dirname + "/node_modules/axios/dist"))
api.use(express.static(__dirname + "/public"))
api.get("/name", controller.name)
api.get("/start", controller.start)
api.put("/move", controller.move)
api.post("/account", controller.postAccount)
api.get("/account", controller.getAccount)
api.put("/account", controller.putAccount)
api.delete("/account", controller.deleteAccount)
api.get("/records", controller.records)
api.put("/hue", controller.hue)
api.listen(3000, controller.listen)